const SELECTEDFILL = "#EEEEFF"
const UNSELECTEDFILL = "#FFFFFF"
const NORMALBORDER = "#777777"
const ERRORBORDER = "#FF6666"
const HIGHLIGHTBORDER = "#FFDD77"

export { SELECTEDFILL, UNSELECTEDFILL, NORMALBORDER, ERRORBORDER, HIGHLIGHTBORDER }